### ISSUE TITLE
Idea: Create a Team page

### ISSUE THREAD

**Issue by evedes** [iamfreeCodeCamp/iamfreecodecamp#2]
With the idea to keep the landing page as succint as desired, we want to move info about us (creator / the team) to a new page dedicated to it.

**Comment by urlDev** [comment]
There are few questions about that in my mind.

1. Would we keep donate/mentor/meet placeholders in nav and add teams and mentor pages? Or just maybe keep the page links?
2. Are you thinking of also having cards for each team member like in mentors? 

I was thinking of putting a max-width for the layout to make the text more readable. This would also help cards look better so they wouldn't be stretched.

*XL* vs *LG*

<div>
       <img  src='https://user-images.githubusercontent.com/56873744/110250852-50085280-7f86-11eb-82d3-9dc79f71f0e9.png' width="45%"  alt='max width xl' />
      <img src="https://user-images.githubusercontent.com/56873744/110250866-58608d80-7f86-11eb-948c-fe1716a03523.png" width="45%" alt='max width lg' /> 
</div>

**Comment by evedes** [comment]
1. Landing Page, with a quick intro. We're going to remove Donate and Meeting Header Links
2. Move personal introductions to a Team/About Header Link.
3. Change the content of the main page to focus on mentorship
4. Header: Main / Team / Mentors (Twitter / Email / Location / Availability / Mentees)

Let's do this suggestion of reducing max-width but have in mind we need to provide layouts for mobile, ipad(tablet) and computer screens.

**Comment by urlDev** [comment]
Created the page with the new commit on develop branch; a8974dc6d85cd598e024ee9fec5647f77d06eac4
