### ISSUE TITLE
Improve Team / Mentors section

### ISSUE THREAD

**Issue by evedes** [iamfreeCodeCamp/iamfreecodecamp#23]
Repeating the same faces on Team / Mentors seems overkill and confusing.

We need a better way to display this. Ideas welcome! :heart

**Comment by ckvignesh** [comment]
Sure, I'd like to take this up, @evedes. 

Can you please assign this issue to me?

![image](https://user-images.githubusercontent.com/61013244/142641757-8da4d82a-a286-4cbc-b137-6a911a1a1eac.png)

**Comment by ckvignesh** [comment]
Thank you @evedes

**Comment by ckvignesh** [comment]
Hi @evedes do. I was looking over the issue here.
I understand that you & Can Ural are the mentors here and there's Dan Bloch as a part of the team too, apart from yourself & Can.

It's overkill, I agree. But before I proceed, I would want to ask you a few things, like

1 are there any other mentors apart from both of you?
2 are there any other team members apart from you 3?

Also can you please tell me what a team member does, that a mentor does not (and vice versa too if one member shows up only under one heading)

**Comment by evedes** [comment]
Hey! 👋🏻  I'd suggest removing the team for now. We'll add the team in another issue focused on providing a great About page.

About mentors, yes, there are more mentors.
Let's fix the cards and photos for now, and later we add the remaining mentors there.
I still need to request their authorization to show up on the page.

The difference between team and mentors: well, team members are people that somehow manage the page, discord chat, etc. Mentors are people that simply make themselves available to provide help and general guidance to students, but that most of the time don't want or don't have time to invest in keeping discord/Github/Website/etc.

So: 
1. Remove team for now
2. Improve the mentors' cards (remember to check it in all breakpoints since this site is responsive). Have in mind the layout, spacing, font sizes, font colors, etc. Check for typos, make sure the links work.

**Comment by ckvignesh** [comment]
> Hey! 👋🏻 I'd suggest removing the team for now. We'll add the team in another issue focused on providing a great About page.
> 
> About mentors, yes, there are more mentors. Let's fix the cards and photos for now, and later we add the remaining mentors there. I still need to request their authorization to show up on the page.
> 
> The difference between team and mentors: well, team members are people that somehow manage the page, discord chat, etc. Mentors are people that simply make themselves available to provide help and general guidance to students, but that most of the time don't want or don't have time to invest in keeping discord/Github/Website/etc.
> 
> So:
> 
> 1. Remove team for now
> 2. Improve the mentors' cards (remember to check it in all breakpoints since this site is responsive). Have in mind the layout, spacing, font sizes, font colors, etc. Check for typos, make sure the links work.

Thanks, @evedes. I will work on this :)

**Comment by ckvignesh** [comment]
Hi @evedes.

I've opened a PR #31 where I worked on the first point you mentioned here.

> Hey! 👋🏻 I'd suggest removing the team for now. We'll add the team in another issue focused on providing a great About page.
> 
> About mentors, yes, there are more mentors. Let's fix the cards and photos for now, and later we add the remaining mentors there. I still need to request their authorization to show up on the page.
> 
> The difference between team and mentors: well, team members are people that somehow manage the page, discord chat, etc. Mentors are people that simply make themselves available to provide help and general guidance to students, but that most of the time don't want or don't have time to invest in keeping discord/Github/Website/etc.
> 
> So:
> 
> 1. Remove team for now
> 2. Improve the mentors' cards (remember to check it in all breakpoints since this site is responsive). Have in mind the layout, spacing, font sizes, font colors, etc. Check for typos, make sure the links work.
