### ISSUE TITLE
Idea: Create a Mentors page

### ISSUE THREAD

**Issue by evedes** [iamfreeCodeCamp/iamfreecodecamp#3]
We want to list and be thankful to our Mentors. To achieve this it would be great to create a Mentors page with cards about each Mentor. A bit of their own history and who they are is desirable.

**Comment by urlDev** [comment]
Making the page future-proof, should we also consider a CMS? Keeping page data dynamic.

**Comment by urlDev** [comment]
Created the page with new commit a8974dc6d85cd598e024ee9fec5647f77d06eac4
